apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-oidc
    namespace: auth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:vv1KxfBxebOuu/XI,iv:YLK0zUofSNAcIE1iJsBV4Rwr5TRb6MwTq1UKmRzw1xY=,tag:7oVyfCMSO/G6vsXzoic68A==,type:str]
    client-secret: ENC[AES256_GCM,data:6nT0oUgrWbRSr2zcwTuF6MCdaO61dEV9lbE+Dsrc8Lg=,iv:STTq342j/uF9l7VhWVNHY31duFGzRqNj/VILQM6XaBs=,tag:IVeODfCof1s8mxPfuaSI+Q==,type:str]
    cookie-secret: ENC[AES256_GCM,data:LvIU0F4nLNSr0w6eBDgloyfh6yf5J6WEHAx1f3LkcXs=,iv:kZvi9nkOdtulk+ZwH4xJWBtg0EbIbIDXxrNLuKlI+WM=,tag:XiKs0MT6CiMC11Uu9szbXA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dkZzTXg4LzFvM3ZIOVhG
            L295U3QvYTd2WnI1Sno3TUM1aUhiZXh4SWg4CmNaa3BoOVArZ0hZd3ozZlJmZEZr
            VlV6Mi81RHpENmdqc0s2MEVZOTU2cFUKLS0tIEM5d21DUVNibndGK1pzNFVReVlO
            ckd5VlN1Skx1MGxxbVlZazM1TVhXUjQKe+diuDLoY1Wh7IIaxQ5chBB9NtNJpzHy
            dOJ64RySP1NwvbBYcfa18HPE5aeVGQzdRg/subHFwDHtBpUdcIqQ0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T16:56:47Z"
    mac: ENC[AES256_GCM,data:c4jw0Vr5S7JbaR29wZiGcXa46nY2L46E21vFb9FyOYGiW/HXE533EMoB7JUzdc2Qwq3D80cZVV+nBua+Rn5JHDj8hgNTn2SnPB+OtKEZdRhqwODUDBBCcZQjcflKHpc03aZCsoR4rw3l4i5kKPD8S8afqls55YIaSxeTdDkavMM=,iv:9UZjj4ACU2It/y4pzSPtwr4Nayfj44AabidFHOz6p0U=,tag:voK5caQc6ClXk/f8JbQ+Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
