apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-oidc
    namespace: auth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:GjoQBSMzSRCsA5p/,iv:U9IlqXtSFjBeaZOgV6AQEuLDmOuHMofB1wk+Kn0hIlQ=,tag:Ttk/2wnChXoHoq/WbDxvNA==,type:str]
    client-secret: ENC[AES256_GCM,data:64zEWtjYenbhPM9A90j0hQZPKNd8QE4XEgkRKfG5Kv0=,iv:fWP4gpnZoRsIcuDY0+NE0TqyRqj/yXOrPmz4jTjcsP0=,tag:OH0lMHcfONsCuqZvB1T/SQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:JAayKczQjpGYZEPKD1mc3I1Fm/QoRtHuJD8cTeeYJhc=,iv:JMTDLxj6N2Y8Pg97HCN2+IdPowjnDHP8YTGaINQV7TM=,tag:ZuOQ6ds94+qkmm82wTMONw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL29YQmpiOTRncDZzclBG
              YWR0bFpaYThRNzFUenBNK0JWQ3FhTG55ajJvCjRyc0JPRkNhUGt4MHF4VzU2TTBu
              LzFXRWlxc204ekxudEIwa1M3OGZHK1EKLS0tIHpwYm5oTUxnRmlQNWNEa05SZzZt
              ZlRKVlN6dGZTbTk3TStGSitUT2FzWE0KvUbyr7d9qSkttzryE6WWMWKziGeBdqMG
              L6Ux366lMPrA5FO8xk3zmsEgtDi/bJQYqdU8PnNNLwUg//rner7ILA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T14:43:58Z"
    mac: ENC[AES256_GCM,data:X6xQgzrJas1IXvouoKEnO1u2NzwYrD9wSGuHc3GlXGhSAhyPaxt+GnEzRXP9IBj/oGKyvthBiVtbh2rpcFNztu32W5i9WnjnZTiuoc8+W4om+1jinZRlliQcFycUeCs/mSQDqqurEiEekkiDWyGip5Jp6EOyuA9zxFbQlyFqX58=,iv:PZdsNW9BcGaPAAgkQv48lY9STqYOdOL9GfXRvmbVL2Q=,tag:Yg03sLTU/cGOed5weGAYKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
