apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:giQxJsY=,iv:IfC1v8Gg2xpmWk71E+hhiWpKwi+fwp3lbtgrG5tG4iM=,tag:O9OL6BvbuLMBsC8aWm9Gcg==,type:str]
    admin-password: ENC[AES256_GCM,data:thTxLsyBs1fTltEPEUWxMjYUVA==,iv:sI9C7v2rItGH4yHgo1tunHdDQdnYV3ISfP4R+qOo0aQ=,tag:3Iaf72R+lT3Zz7m99ER3DA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT1Fsb0kzSjNENmVVdmpL
            bmdLOHF4TndDU2lTeDNtaXFTTnhJdG91Tm04ClBDWjBJd0ZvQjE1eFRjL0IwZUEy
            NDZ1RDNSTE0wZlVJUXpSVGxSbFpNOXMKLS0tIHd0SGhwM2hTL0FIb1dUS2JDcEI0
            Q1JpWW04aXVCTkM0NkRzdTBLK2FmMlkKQHtGWAYlfBh0rb4tyP6WAcWqwwfXGi/O
            AXkIMPGqGNm2rSAn1vQjWXYSSd/iw1P566Z+1Zjvozmnba4V3EprVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T16:55:47Z"
    mac: ENC[AES256_GCM,data:boqWfg16G/uFjyVEI0ygGFfYy7kYkDP6JLkockAGlIFkXNx3+w+j2v5m0WWJ3Jz6el2/aMhjoXuThIwGvTU/vAko80AZIyHCQIbonxU8Wuog+g1gqnfHHTnuljcQjWhBhrc7zHZh+6s0FWjrFta3sDsglrhFePbQ9fRy8vYsUVE=,iv:s44MEwAp2YZ6n7WafTGtmyOXuPI5VmwMQ9qrGiMcgLY=,tag:G7Y8ajCsR0KfFfCQa6Pf3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
