apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: observability
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jTbUiJu35ihbA6vSJGUd0zw/MAF86T5mUz5e2P/4fmQ=,iv:YyNWniqgLA0u5H9z7unwVRVCizLu/KyTZFGQU79EUzI=,tag:0IhBps8PtII91C2BWUbxtQ==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RXlZRFpybVJOK1ppQUYy
            NmYzc2Ezei9OS283bjBaUWM2NnNJSnkxOEdjCmFsdEM1cXk0R1FURlJnMWRVelJM
            ZFBoTU04ekNJKzlySWNRVnFOK2FCd00KLS0tIE9ZZVBxcEhzUnh0cW5WWlVIMTFY
            MUNZck1DSEdvTHVTZFBkVnRkNTU1WGcKcJTqTHTgji16cSLf3aOf+0rNxcZfewol
            Eb8I9hbnMXlgey8pk2GlbKcmvigHuUBAz+HktfVGCkOrWKglZhnJbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:02:29Z"
    mac: ENC[AES256_GCM,data:JYujJ8fUZZmVYM0LwuI1az3rQ6RiUcPGgAkg9RHY0oaKg5CfFGLL7iXucXFKSzcLSNFs64quffsGK8B0NCtx5QvL5dn0KpCEcmV1fouX/vqkkcA9tFqTWfd/nxkXEphXTQyJlPSlw4jjJT8KaqCpQ922WPShT+37Auy++0fnJCk=,iv:Ky7U8WTm5rL0x3F56kxQ1tFlbQscEy3xNrz/LzUMS60=,tag:nhSVoVjtItz4SvC85dB9xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
