apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: observability
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:k35TldMMjSvUR6f6vYU1MMEEl8qJSqaUUmcbCGjnazg=,iv:cdhOrKy0yFgsKpsYQJpR/Gq6HMTEYyX5xQk9yAGwMjk=,tag:CPkNqe5MklkLTUBphqhYuQ==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTI1dk1WS2NCNWpjZmgz
            Z0g5b3YwUHRxUzRhRzYrblpFNjFxaHVoZGtBCjg4ZFZtVTBhbGZHc2t4R2kwdDVV
            WlIreWM5Yk41ajhyS1FPVmJucWJqblEKLS0tIFpjeUpvMmRKYm9IczNxYzFUVFdh
            cVN2emk4OXczcHVkRW1ldFFIMzFqTnMKGD86H7/piEWaEnkelc+6+CXIVtj0stec
            4Vuvanwx9McEfPWLbMJo2njDMXS80OHqlYDELaKP6xXvtEnJvIrhGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T16:56:05Z"
    mac: ENC[AES256_GCM,data:R8TxMH6oICnbwIbkbUI4Lya+9qEbvTXEjR5pMudbJ/hPXx/zROJBGeha8dAwzdqSjgQP71pqALEqsn7GYiHZHYt/mXBFACEIXxfC3qCyCVGHGGDbIGOhvyf/UfHQpVKoBKiP1lZs+m+bsv2pxrJ9JaWzNY25sNIFIGTKZ15IBPc=,iv:kgN7luIqrFp8iD8CcbemWvFapH46ijSpnIpRFucjoy4=,tag:Vr3ngH1fnhHjWTwP5E1OZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
