{
 "title": "Raspberry Pi Cluster Monitoring",
 "description": "Prometheus-powered monitoring for Raspberry Pi clusters, providing insights into performance, resource utilization, and node health.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$host\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "up{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "up{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "up{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "up{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "up{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "up{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "up{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Status Trace",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "up{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "up{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "up{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "up{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "up{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "up{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "up{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "barchart",
   "description": "Total network traffic",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"})) / 1024 / 1024",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "bargauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg by (instance)(sum without (mode)(irate(node_cpu_seconds_total{mode!~\"idle|iowait\",instance=~\"$node\",job=~\"$job\"}[5m]))) * 100, \"host\", \"$1\", \"instance\", \"([^:]+):.*\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "count by (instance)(count by(cpu,instance)(node_cpu_seconds_total{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}))",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Network Traffic Trace (MB)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "label_replace((sum by (instance)(irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])) + sum by(instance)(irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]))) / 1024 / 1024, \"host\", \"$1\", \"instance\", \"([^:]+):.*\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}\n-\nnode_memory_MemAvailable_bytes{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "CPU Temperature (°C)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.201:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.201"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.202:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.202"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.203:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.203"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.204:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.204"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.205:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.205"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.206:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.206"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.208:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.208"
    },
    {
     "expr": "max by (instance) (node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"192.168.88.209:9100\",instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "192.168.88.209"
    }
   ]
  },
  {
   "title": "CPU Basic ($node)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "avg by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "avg by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "avg by (instance)(sum without (mode)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=~\"$job\"}[5m]))) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "avg by (instance)(sum without (mode)(irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=~\"$job\"}[5m]))) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "avg by (instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic ($node)",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Network Traffic by Bytes ($node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Receive Bytes Total ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes Total ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "-node_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\"}/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}