all:
  children:
    # local:
    #   hosts:
    #     macbook:
    #       ansible_connection: local
    #       ansible_host: localhost
    homelab:
      children:
        cluster:
          children:
            master:
              hosts:
                alpha-actual:
                  ansible_host: 192.168.88.201
            worker:
              children:
                computer:
                  hosts:
                    bravo:
                      ansible_host: 192.168.88.202
                    charlie:
                      ansible_host: 192.168.88.203
                    delta:
                      ansible_host: 192.168.88.204
                    echo:
                      ansible_host: 192.168.88.206
                object_storage:
                  hosts:
                    kilo:
                      ansible_host: 192.168.88.209
                database:
                  hosts:
                    november:
                      ansible_host: 192.168.88.205
        standalone:
          children:
            iot:
              hosts:
                mike:
                  ansible_host: 192.168.88.200
            nas:
              hosts:
                sierra:
                  ansible_host: 192.168.88.207
            # decommissioned: no rack space and insufficient power capacity
            # hw: x86-64, 32GB RAM, 512GB NVMe SSD
            # builder:
            #   hosts:
            #     romeo:
            #       ansible_host: 192.168.88.32
        proxy:
          hosts:
            hotel:
              ansible_host: 192.168.88.208