apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-db-secret
    namespace: sonarqube
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bgLDuAYOmn19,iv:C58JqlqyFSFq/tp/TsSDZFE4HHEthsJmpH5J729VMYI=,tag:Vmx21gjwPiJkeK0cZG92pw==,type:str]
    password: ENC[AES256_GCM,data:IRMApy928K1QT99KcD0WYI75FA==,iv:I4VFPBaJOMeSdaQT0FvS7Ltio1OmNaggJDATD42rFMg=,tag:ljc7lHhDKYtQCCwV4vlpWA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweW84Ylp4Ui9HZkJUVXBm
              WFJPcmlXRk1SZWs5VnpZMlRzS3ZwVlo1UVZVCk9XRFRVQVViRUFlcGh2cnRaeDdF
              dWZpS3NVaWhya2Z1SDFoRlhkQytCM2sKLS0tIHpiMFhUWEJrdVhTa1dnMW1QL1lN
              N29NT1BjeFRySllBamY4OFFqM25ycmcKa0wIvi4N/ffuq3nVYPNWZEdod91z96RJ
              rdOvyEUFeN7+hrc3RbidHkP93xs+Ny2SIRoLJQVA/Et861ywwz5jdg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:51:53Z"
    mac: ENC[AES256_GCM,data:bmwjl1mCxgo9Avlc2j/KXTwW8fOkvU270bX1yxIwgHyaJ3hecGhFiNnYYw+kbScdU+KGG37IC4Bd4ZTfnFoMvdRp/rhkTPTDigpycVahf42OYZ0pkHblS2W2akLqXz1SCEqdvjm/sK0mQxHBb3OcsSXJ9F7Q2w1J3XoRsBqJeT4=,iv:Q/BLhONyhSshHAMOH5CerPTcldeZF+leCqJWyjAiEIk=,tag:s+sRdfNaYS0tLNK7N6pNGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
