apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-monitoring-secret
    namespace: sonarqube
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:ulTxUy5Y9Cm0MiAPpRKmvhaBca1echyirZ8=,iv:IaHKdecvf2gqWtQ9w22cbyth+ZqGw0osl3VnVgrafZc=,tag:KgNQjEw+txB0t1Mr9ronag==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN2xxZ2RxRVZIRys3a1RV
            TjhRWnE0MU9ndmpmWTZMTVlqWDBEell6VUFvCitOMDNMZlpHRG5KSkloM0JPQnFu
            S2xXMmZEUFhMNFBUVDMzSDZpYjBGZk0KLS0tIFloaGNlTzd0T1UrU1ZNYmRiNkN4
            UkNuaitPRmFIZC8yRDJ6b1hmZDRCSTAKFG8YACxfcIxTvIcfeJFLLnoOWO7Usdpc
            5StHHitw9spwIUFESZRPYA4tJMaKiTmG7ZErC2JHo+WhmA8goJrVHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T21:57:12Z"
    mac: ENC[AES256_GCM,data:Z1OIMh69EdlUTpKRsOwx/PpeVcUGwQQJ6jvqJNZLz86l9f16ElDhSJrRZFS93/9hGoxdSX88SH3hH0fuotTdPffK/ecMYLMLI4xYggMwA1FlgI8/Ut8lFFDdiKJ2aEwjEibYdZpRF6sNtRYqnNWlM6J/DWic6gasv9gq4vb65ns=,iv:8Jr0wgbTJ9XevUIi4fdKvufKmaj8qp7PGmCfWivjIAA=,tag:OUxM2fjpFh1p2WM6iAUPVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
