apiVersion: v1
kind: Secret
metadata:
    name: oas-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:QVKttosNmtSt3gyTjOKnhfwPCpNPE2d1xezBFHwmxzh7t59q5HvMB4w3v2qzTL74dnJ2hFFelmpzwi31ecAV1S5DYowYdu0MWBHVK0XZEm3SyLKJsjl2aZvEO32jonX683y9ak1TlnFKWBe1JdS7ZSzg7t1e2dAKZuwHtXUB7i/7ao0TGxx7wTgAVNdJuJgfH04rb0rjnhFSkbvugAhx0IxBUJe7wRi4iC3J39MIxkSTrKdgIB4WPHUyPJFa9yIOMxQ29sjo97xf0sbGzWEVk/aY6FbpCFdpvtgS37dYG85KEsjdRk/K7R7o36oXc2oa984iSk6tZwKx4N+DNNM+qipshJRNdf9WzK86qixH47eMdqkkyL5wCSn5Nj+KmufXOkXc5sF0d68mebfQu4TOfpw2gm+vYk7pzbMheEJNnnjdFnq58KG5OM69X3khgJf2gIhRAXpFbgjI4slbuNvgNpy1p6CCdtBJAyd0DLJ4d/ZtIiOj/h4h4FxuuNdaviZYnU3Fj836MtEoqQftjHUs9U4oeL57fNTiYF54ND3dX0anhQHUgOQc8JWO4wVjBW4Juj0td6RxeoYdVWNqF+eOvbBUEzp8fFQE+57Ru/YtDj2tVY3J7dQ3rItUb8QDyHzwT61Lxdk2KhTN74r+QaUi5p9Ha7Skcit/n6Jjb7+eG2XZGgv/5VLxEs8O5WZ6pd9k40B4uRms7NGA+gJ0SEEIHvyF19UkOgjqVj4mnqxcbrNLxb9o9umTuUJjpUjg,iv:uFzCvSR53Z/TjCoQFATGMg/YivCYyL3NsEkqxxkVCgY=,tag:1K/iGERLv48gy4Ys8uZwVA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZDRIM0xEdG9sa01mSDRk
            aFZCcFhWZURFVjd2SGRkUE5Ma2t5NmRHL240CjFNdUZJbmExN1NQcnNyVkd3bllQ
            NFBZZ24yVm5XZUQxc1Jwc3VURXZzNHMKLS0tIFJTUUVHc3lrSisyd2ZTNi9YU0o5
            b3l3Wko5YlgzQzhQdytYR0xMVnArdjAKcfl81cVNJ5E2wOrFZC18mqc9tTyEx13r
            fI9YzXgCgB+JS9XIDqytaUz1XCuXv1JrblVtxCcqDeMxb0DqfBm3/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T12:34:46Z"
    mac: ENC[AES256_GCM,data:6pxSlHdijTTrIf9lQHw3vYzoW3a3waxXWR0I0jzWUTbgE1h3gsRSwhc5X71PN3a+bTmqe94EfFObDG8bi16gI2wnx/WSV77d98y6mrr5ouikWf+V5AZdI4HmkZt62CBsKgThUSo8FiJA1Ua0q2VW/VbG0l8NfdkXROnE0MC1mdk=,iv:Yz/Vt/wP4UvMVPKGlaXZSen3YeZuIhFBE2+7z76vkek=,tag:8natfg5+d5jSGFr/GI62Og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
