apiVersion: v1
kind: Secret
metadata:
    name: oas-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:ly/zaJbVAe0lzRdKp/KOI+P5sYdpjb9oOGsKz/lenlBeBkpMwDhH4SuFHsp/OCSAL4qkARtNbgDmV/2JXEkTPukF9tZfw2fkgWryykRjusUbbdVkQWBVhXrQMlWlKg71QAxo9uzwTAxyLYfQWMFIS8YESqPArhW22ZN2FqucDFNh1qF5hIi0tFl5SYYo2PqwwG11ncxPuPY7fSpInCa2c3V21HJDP5jg3gyc7qdhvqOekJ4usCNLNuUFM6P3RQaRbckuOju+jQHlJR1oa6MfY/aLNqsh+oQbTP5SQ1PAQ6LxwwOM+vqXQl0ntAM8wQQ8mIUnv/HF5r3aYkGFl+ZZ+vucObtJ8xg64bOFg7rKO/mMyuKIuENXWJb0gwX+Np44PMNXLKqTQrAJuklyb6BXD2qGCixFhMAZD29xnVFwxsbLg+Apx6G38kLWyhuvWI4kYEzSuicxK4RrscGMxXywOtmo8cA4Ln04V77qNvpfoVipYrGitCUczV+fjcW5FOOB+D3WFCzryoC8VqtNhzVWN4MA8HwljpGr8SoFf8Tb8SoMatkE1Le74yhx0ecrXQjQidrC2mqmh0IGK0ul2suHmGb8iHY3lyIVND4mRm0gu3Z1xuv1GgjMaQGc/u3HOYIm5W07nrwubZDTYTAmDHZYIgiDFNzuMa2mj+Pkp3H4mZKplOqaPXLfCfAIAsKO9A6erwYy97NVpP1uZfjCspmKzQtnooxFce2/c8LssAayp+jz/YPBLOeQ1J88sRNegdY=,iv:u1SA/zJifNYXceLk3aVUvDMfGud/FcGx4VrnMsSeuM0=,tag:Ea1JnkYnHgdyABZYU6LjmA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVBwclcyem84UTU2MHhn
            RGN2c3hTOFFVNzVvL3ZMME54QnBFenBscnhrClk3eUl5a2tOQnEweS8zNXRMc1pO
            WUlpZ3lZQys3THdpMy9HT0cxbW5HeEUKLS0tIHVOb2NqZDg3MkJnRmNJTUJ3WFl2
            dTBjNXJUNmtMMHp5bHJjZnJJbzkwSkkKpYM+M1/WnUpbFQ8Up+bJqHOruzHMYE4u
            YuolDVDHoZ6EnQxKfJ08/hf38+Cguy/5QVfqZAktDjjvxXM9x0iTug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:40:31Z"
    mac: ENC[AES256_GCM,data:oVvo/lYeXpjy/oH3GCocteqVlTzRQTzEMOBL4SoNCidAJSxLoCrt1q7gok1VbO+QeQj5hGQS2MWdjlUUn6sbSPZ0zgS6OJ2civpq3mzd1Sjcd0hZuutTcHgG5+jUYJR7UXLllR1km7FmGdDye0aKCDPkRJLSFHcYq+PD6dfJvzE=,iv:RQUsmyV6JMiVqTT0t1h0wNjm81dx2h9IEsgs70a2sJI=,tag:Q+5eJMi9sECdxTIvAdekNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
