apiVersion: v1
kind: Secret
metadata:
    name: oas-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:X9or/JyyRsU+n/u7redIyjD6iM7/i1Rk8cARWI9hQryUEKAjeIIQZqepPF5QREYl4txvRU6zap0WGEvqxCPyVOZB2IC8VJNV915oFuLohZCp33/XvynJASZEiKRHct8OEE2q+3IsyeOCPLjq+JqD+Aoeu7kuWiPuSd/RihvWULhdxQRCPvxClb/C3YemDg91X65O1iwHUy3qzIgyESxxCEB+8F2QD+JGRiSHqNMEMnXGTVHgiAQm91iA2pP1A2fnJoQUIM/TbroEeq6wymcirgOmKTyfc1dWmOAmbkLb4iEhr20gRvF1H5gzWtGPoTdpEVykEJdvO/dz5OfWN2rwoPNVia3N7Wi4U9RkR8Ckgceu6xb7QazXaMVVvdoX5YlUf2kXxNNy2xf+WivrRAj24/MhR3F5QCqilj7AVn0WcVKwLdeRwXEsWqXQlmOLxiy1aVJyUOKEnsGtC1WCWHNDYnJ04jHzSAbWuC65MUOxvnXfN4C0k2G1sjAU8gf4IwyP8MtQSWr3YYzHtcME8YFI97Erciwcmm8FdOTr271KGyjfsNW1XiO9CSJwKkAYKrHh0FVG7LeHl0/NYDlun62RC1d615O8oFBZqc1XbX1wdDKW5jy2dMjiot4+WjyQnH1GCK0/meKtt3xxtrHko3KIb2UFsqxXCuQAL+k4nNzUf82CxDjGxSIvewTkAl3d7r619GbvoAKylOsNV5d0LllemRTkNi5M8MtDlb7CHgJYlH76bWJwZpfQj0MMEWBoeTA=,iv:9MiiklB2gxXwYTlRHJAK+/55uaipdWz2XC9VQzHhu0E=,tag:T+vAD3fMvHBmEWW1jhZF1w==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOUg1ak5ZazN2RGlnWlEw
            REk5TEZJaUZqVDNNOXFYcEpPUEFoRmx2cG1RCkJpVS9uRlVRNzBkclo3UVF6blRD
            NlZyd1lrUWt5cktvYjhKWlhNVVNZZWMKLS0tIGlvL0w1UFVhdVNONy9kTDVMUFNl
            eVBnU1E4Mk5tK2d2Vy9kMkIyaWhHK1UKd5noNaIDLMR7HNRsprLkm99lcTrdksHN
            Nq8mT6tr6l4Pr63iQ2zSkrmzSAYkYa5NgGDM55+5nhDtwsY/ZxhIeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:47:54Z"
    mac: ENC[AES256_GCM,data:+s5knQtwQ1eXbkMNbepf4R7QEPZpDM9jurCZigvwPp7lUIJv4OIy4mq3YxyNqw8JRGNuhPsFJogMkvTlN5cBtB/ZZBHCtqLhNbl8eiqPArU4g5qw8a91ssVj9hM9XUtqgRcVznGHKfd/hu5BRu7C4+7KKdK1pC4uBTpFjFCvcdM=,iv:b64k2M/Y3nLWpzUoUjtAQ6cOG/mu3jqy703c3lNw7Cw=,tag:gN6H+9EbdUN2b0B+UbDbtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
