image:
    repository: zot.lan/kitti12911/oas-sandbox
    tag: "v1.1.0"
    digest: "sha256:7d26eb837864a163732a17fed47a9870a8196f789bda59ca044b27cf8bfe2c87"
    pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets:
    - name: zot-pull

resources:
    requests:
        cpu: 50m
        memory: 64Mi
    limits:
        memory: 512Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: oas-sandbox
              app.kubernetes.io/instance: oas-sandbox

configSecret:
    create: false
    name: oas-sandbox-config

probes:
    readiness:
        enabled: true
        path: /health
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
    liveness:
        enabled: true
        path: /health
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3

config:
    service:
        port: 8080

httpRoute:
    enabled: true
    hostnames:
        - oas-sandbox.lan
    parentRefs:
        - name: traefik
          namespace: default
          group: gateway.networking.k8s.io
          kind: Gateway
          sectionName: https
