image:
    repository: zot.lan/homelab/oas-sandbox
    tag: "v1.11.0-beta.1"
    digest: "sha256:2d407de4f7a573415d90a934c3754704f83899a020b5923b61619ca676eda614"
    pullPolicy: IfNotPresent

replicaCount: 2

imagePullSecrets:
    - name: zot-pull

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 50m
        memory: 64Mi
    limits:
        memory: 512Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: oas-sandbox
              app.kubernetes.io/instance: oas-sandbox

configSecret:
    create: false
    name: oas-sandbox-config

probes:
    readiness:
        enabled: true
        path: /health
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
    liveness:
        enabled: true
        path: /health
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3

config:
    service:
        port: 8080

httpRoute:
    enabled: true
    hostnames:
        - oas-sandbox.lan
    parentRefs:
        - name: traefik
          namespace: default
          group: gateway.networking.k8s.io
          kind: Gateway
          sectionName: https
