apiVersion: v1
kind: Secret
metadata:
    name: redpanda-users
    namespace: database
type: Opaque
stringData:
    users.txt: ENC[AES256_GCM,data:teuQ2gwQPd+xFA3RUoF/zu9LsIBELrPr5Z0xemi5tNurWaMSwUE+uJNIPMo9rTcotVvhqjO+ylp6+oVUd9C5lUclMz55GIfreQQQJ+4C,iv:RqfNKILZCF2wn9R/Koxedd2jwgmO+kP9aEfpYCuwCcM=,tag:duL9NZDhrKrl0qyF9VgG8g==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcy9BZ1cyOTM0NDFNdVRL
            N29GOHJsUkNla1ZBMXJudCtySG1zNGxKN0dFClRJTU9xK1pwZ1hSZmhLZVBtMWV6
            eEpRMGJHdmE5SkZjRGFrZ29JUHdqa00KLS0tIDNCVjN0cldyR1plQVdYVkx6MDdR
            a0J6ZThHcC82WTA2Qm9ubGNpc3gxVkEKAxCFwQ4JtptzLFsfxbLXdRZRA61tzJIX
            6rE1uNsSVZK3IZrpx32tqL5v+qLh+hSD2ch7COFUuSq+A2wUFMGh7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:10:22Z"
    mac: ENC[AES256_GCM,data:OhKfim34tMa/kal7rau5uilt7V333Jln19bt7mUByhKfV6FVPS+7/NsFyD7vRRjXcNsVx5D0w0BFuC3SVliHb11PUOcxfe4BgoHUx2Z1y5p/jOtLxs7FjugurhvUJT6rO/WGl3sdIe8q/RYd9/cqgxTpP1loJs9qqkbpAF91gto=,iv:J/C2tj2miccGFOfJWlRybWEypw4Jb6hYLSmtG4XFQPE=,tag:zqY/UFhnJVs0+ky8W3Cf4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
