image:
    repository: ghcr.io/kitti12911/payment-sandbox
    # tag/digest are overwritten by the payment-sandbox release pipeline
    # (scripts/ci/update-helm-image-values.sh) on first publish.
    tag: "v1.1.0-beta.7"
    digest: "sha256:e96da2c150651e1e6aeb1f55ecd4ee8ce06c006a2d1889879a638531a0b93bc3"
    pullPolicy: IfNotPresent

replicaCount: 1

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 25m
        memory: 64Mi
    limits:
        memory: 256Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: payment-sandbox
              app.kubernetes.io/instance: payment-sandbox

configSecret:
    create: false
    name: payment-sandbox-config
