apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://github.com/kitti12911/homelab-devops.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/app/keycloak-operator-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
