apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: "26.6.0"
    path: kubernetes
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: keycloak-operator
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: QUARKUS_OTEL_SDK_DISABLED
                value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
