apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: database
  sources:
    - repoURL: https://charts.redpanda.com
      chart: redpanda
      targetRevision: "25.3.2"
      helm:
        valuesObject:
          statefulset:
            replicas: 1
            podTemplate:
              spec:
                nodeSelector:
                  node-role.kubernetes.io/database: "true"
                tolerations:
                  - key: dedicated
                    operator: Equal
                    value: database
                    effect: NoSchedule

          tls:
            enabled: false

          external:
            enabled: true
            type: NodePort
            addresses:
              - redpanda.lan

          listeners:
            kafka:
              external:
                default:
                  advertisedPorts:
                    - 31092
            schemaRegistry:
              enabled: true
              external:
                default:
                  enabled: false
            http:
              enabled: true
              external:
                default:
                  enabled: false
            admin:
              external:
                default:
                  enabled: false

          auth:
            sasl:
              enabled: true
              mechanism: SCRAM-SHA-256
              secretRef: redpanda-users

          console:
            enabled: true

          storage:
            persistentVolume:
              enabled: true
              size: 20Gi
              storageClass: local-path

          resources:
            cpu:
              cores: 1
            memory:
              container:
                max: 2560Mi
                min: 2560Mi

          config:
            cluster:
              partition_autobalancing_mode: node_add
              core_balancing_continuous: false

          monitoring:
            enabled: true

    - repoURL: git@github.com:kitti12911/homelab-devops.git
      targetRevision: main
      path: infrastructure/kubernetes/app/redpanda-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        gateway-access: "true"
    syncOptions:
      - CreateNamespace=true
