apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: observability
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.24.4"
      helm:
        valuesObject:
          tempo:
            retention: 168h

            memBallastSizeMbs: 0

            extraEnv:
              - name: GOMEMLIMIT
                value: "920MiB"

            receivers:
              otlp:
                protocols:
                  grpc:
                    endpoint: "0.0.0.0:4317"
                  http:
                    endpoint: "0.0.0.0:4318"

            resources:
              requests:
                cpu: 100m
                memory: 384Mi
              limits:
                memory: 1Gi

            queryFrontend:
              metrics:
                max_duration: 24h

            overrides:
              defaults:
                metrics_generator:
                  processors:
                    - service-graphs
                    - span-metrics
                    - local-blocks

            metricsGenerator:
              enabled: true
              remoteWriteUrl: "http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/write"
              processor:
                local_blocks:
                  flush_to_storage: true
                  filter_server_spans: false
              storage:
                path: /var/tempo/generator/wal
              traces_storage:
                path: /var/tempo/generator/traces

          nodeSelector:
            node-role.kubernetes.io/object-storage: "true"
          tolerations:
            - key: dedicated
              operator: Equal
              value: object-storage
              effect: NoSchedule

          persistence:
            enabled: true
            storageClassName: longhorn
            accessModes:
              - ReadWriteOnce
            size: 20Gi

          serviceMonitor:
            enabled: true

    - repoURL: git@github.com:kitti12911/homelab-devops.git
      targetRevision: main
      path: infrastructure/kubernetes/app/tempo-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        gateway-access: "true"
    syncOptions:
      - CreateNamespace=true
