# renovate: datasource=helm depName=trivy-operator registryUrl=https://aquasecurity.github.io/helm-charts
# version: 0.32.1

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: "0.32.1"
    helm:
      valuesObject:
        operator:
          scanJobsConcurrentLimit: 1
          scanJobsRetryDelay: 30s

        trivy:
          ignoreUnfixed: true

        serviceMonitor:
          enabled: true
          namespace: observability
          labels:
            release: kube-prometheus-stack

        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
