apiVersion: v1
kind: Secret
metadata:
    name: grpc-sandbox-secrets
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:nVCFsbjtEkBrIctS,iv:PUbbpF1bXv0n3iy+I07ZKKPbTz42QCN9nL3zGihdRZU=,tag:yz6weUV5iuP71LeuoytNTA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3PvmTzrTWnalsX+VZknxmnirBsd4ixxvCzI2yI4q4ow=,iv:1pjLhE7Qr8Is/eg/keoGUbxJ7yytCkFrerQAmkLHL5o=,tag:kHtgXtjYatUlX4uNl85Yog==,type:str]
    NATS_USERNAME: ENC[AES256_GCM,data:5Dgh5vA=,iv:heMnWA8OSMGlNrgRfrAhr2UhhKmLuNNG2vAjODqgros=,tag:socHZTODuGrquCyZiBuMeA==,type:str]
    NATS_PASSWORD: ENC[AES256_GCM,data:94/+rgrE2dwEFwLJy0AqaNpwTQ==,iv:mzTNxPGXkAlBI/M8KpfuMII1HlP1zePwf3EPHUEpPeA=,tag:xuIPgSaZvHizM++V/G8GGw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT0Z2SWkrTWkxbTVFdnpB
            Zk8yaER1TVF4a2xCT2VmcFF5SThFQVJBdkRFCnIySnJJNUZLK2w0UkdkVkhocVQz
            MTVPMGZ1aVhoNGx0NlIwVTRYNGhnaGMKLS0tIGV3OU1nYVlaSDVtbENkNmhBN0wx
            UnA4TUh0Q21sRUFmcllzQVVGUFJHWkUKwq3e2Rlxqc9wg0kFV+Tt3ZWt6uczAvDA
            G5qhyf2EOfhZ4ndO9Tu40aBFML3rksezZ/FtnAmB8z2RrNlK2thyHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T10:34:22Z"
    mac: ENC[AES256_GCM,data:9r6cj+RS2o03uQ8hU0+/Yu5ky1hXb4prCH8NsHerHrpXwhWd0s7oBimp/J6IRN50c3fzarLnl4DYHoMfbDt9CnODc4sdoQZ7crq61HKM2W9bI3NPcHxjfT1Zlvxp84ECoZN/sg+H3LY2zvNjZ/G7APMj8exfpfJb0j+sXWkrB0Q=,iv:kjnb73fxgn0pyRPcoPPMG2FQmhKULrQOeybJFW6vI58=,tag:ChVKJwuE/zdVI8FSFGE2IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
