apiVersion: v1
kind: Secret
metadata:
    name: grpc-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:4VKDoFAn3K4j57ack45SbPcQAILkWgcsnglkGgTYbVUvKU4KotNx0yNy4CO4IE28ob4B6SI9lsRvb1UhwWdgthp4cjnOgyEEGpA7esiqWYJU9ra/8P/UzTR6tidP0mZJesFzYnVRxpv0JezPDf90zoufX2105AEgwkB89GR7TktS6MBTYmmcHxTEYF9QnGMMa5EUFQ0LpwXeKAJLyLrLhakk66/FyacnUauSJwhBh1s4sRDRX62p4opQ1Jk+wlxiDFMQF40JxGDTtfzMBjtHVIC82Q9cczgbFE7La/aWdFHqplf/GKqE2Z7pNw8E6ScW6EYmq/ILQQIgzk1FWHktYindTwoINiC1MsLO0OLrHsGW+SBIepRNMTq/5cX+T+H5mvyEstLe0kMs2m6aCC9LNzvXretwIlzuQ+zJWwbvQBBHmP6+JXO0WmC9YNXjlmtKGd+BIsmH49xw/RWweggML5rsUUIkEmKWQZBKRmYZsoBfGQocCPQs2sYU+nqJNPLx/QXRLH1nqBxFSZ+Iw+KGZD0UGBl1L/FziQ/7Ix1HmOCM3oazdlIG9vEDsLi7p7LUY9374r7PySWPxZeUpIeaqkH3kKTd2g1fr7OlkCFemH0wo/Xl7shQKeiXEx7Kz8U5lf460xQUDCyST6vaEdT+bDK5qYPsFhn+3uC6CcGHt93ELoYFFfMQ8SAGUprdYOGQfCtTUbZd0sLZmCoRzgXwYYOZ3/XDM/s7uH9bkzbkGW8DSXuvYo/w7YGPIABIIcTsh47DuQkNQ1jh2cqZIRP/2ivezfSuNaO4FuwW/KFgisut9R8Vgf7sD35twNAjS4ZDe6LpEddUgpbXjFNfcquyPGMAkt/jJjvwZnD1aNqYkKzZk4o8rhmOosawcx2SUrKz/6kn+CVHZ944TtWJlsDrp42zE3ToOjaSe4I9RNGf5D2LbHX1VqMbhtjLIO4aRsO57ZFlcL+cvAA94gCeJyko/ZDv70E+XPJm68hQVuxnxwIvOThIE732lBBYFmrd+9XF3GrLLY8IasvZi3WzJOC9XAn8/+I1nt0iRSeK4/GnlS0cR0TJV4sN1UEhfbKXB49UKNp8rhm6bdv86asfjUrtfw==,iv:rpvnOHgc0B8xoOp+k12Z4fNV/AaDc2EQSLh87u0oC8w=,tag:NmKIS93Y7wRD2R2A/9poxw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3A2czE4RW1tY3BYVEEw
            QUNybkp2YXBCWTFRMkQ4NThGSTBpWXJWNkI4CithZXM4dWcwRzFPdkhESTVwSFdL
            Z2h0TkQrcTFGSU5nVHg3SkwxaTNjNmcKLS0tIHJhQXNMTmJRMmRiL2tyTllDWlpG
            SE1DMlltZlF3anZudHBTQUVhRTZUd0EKzJXCfVTFmVRc40Z/8lGZfp2YWTMzRaCm
            /uKnq2Ix3dRdkUS5CMrCJ6ZwltM2q5LRE7ANP2oDURgLqyLhuCPOKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T10:40:43Z"
    mac: ENC[AES256_GCM,data:o6PNZ4pLAtCyC3g0osP7CsQjkzTEnu2hWzz9/WfmRruvGuFHgi89Onhjfv8Jwm/8Nc4q3STwTvI2kfqrfE6q1Ghb60wwMZOCBgC5fbnw+SXRaOPPYKkvFD2Fn2ZJp71AIoVFqHF4Rs2NJGURKbLsxQvCWjRhTRWZ9L8o2lhzzTY=,iv:3VZDsaiyF3x+tCWIyVbme1P0WRCuh1tssmq7uZOBwMI=,tag:gskRLAhjffisVvHC13U1Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
