apiVersion: v1
kind: Secret
metadata:
    name: grpc-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:knng+0dCSq80TY4WhNJPnh4YosjN35+H7OLLgB0KOW/mzganiyKnLzQxGmnBIhmNKRyTcCTa6++xYkgJVe8HbL24aD0NtS1TmqKJfRd2y6I71odn0DQuCQ+whJrO84f7MG02MfnPEwUGB8bxOwxQ4ce4niWDfNi5BVqpJI5DDgW/td0RSKP4olSXbk3zk7ezOA6OSuHkK/soBcpf+ZWgmza32VWpt57zkjC1LqQBg5yvVxI86Pxmpu/zLVfU8Q34BANAtuG04s1GkcdiCOiP9Tze13vJdhAP50pUyRhQ++GQN5If3lOlRgTyyGtE3DJYB/cDPW4tkpv3KQO26ud0Ftp7XME/jceDdMHAiV6LDFeXhx19BEXpe6v2afF03oLO1UJY0LICEWnVT8mW4exja4ANhb+6Ox0mG4R0GVluZaUFvxTPXrkuMtlbHLyLqHSn7bh4xeam1XVRWkpGUvUD0Hh0yc1ZYIL0R+p7lXOhu/iECxfo1XqytlNDO3X7COqaIzFXlO+0FRmmPyccUvPdJ2DNjjwTCfIbU37+NquLfRytD1WZeerzo2CIMdLe/zr2HhMBxbvog6jk1up8z3CadzIOnzXb5khmQcRPs1iI3JVPbep1kQNlfXB7cCRuj1d0+Zhhja7wv/fPumKu7bjpJ4rCt+k2/ED+VGAN1lAGJoaCE6Vuse/5jlr6zxDR2XTv1oKTrsNJws5kw5BuPqRnpMTogckghyeprENIgWrr+Tdye9fXIX0hFKO4nIYp7yZmsyGYbKhY95tN7jL8eRhwWYjv0bPC3oiCBN7tWRnOOkW4zD2PgIzD4yLFe2W97cu4YieHzBJVOM0RWr+G6wZjJN0Q94i+Bd4F3Gk5J+zX/9rbv2KfsAPwtxgd4Tnf1RzqNzgdPmT5l2gHRoJGTVvPKK8JjZ+ArxACvHphHnHzUycBl/0f1S+xhOnaIK2qJXFCP0in5ugc3WKgSP+/Xgi1cyn4Ys1nkYWEl4ku8LqhKGvS85Cp29DJUI+bhYrA091DJh4q2BYUcN/a6k+npBi7AT7suCBj1FaXWGkLAVLV+hIiNqX639bBLiVOdZ2XaVKSQBZ4J2GYk/ZmP09UPYsUBvf/PgJ8,iv:lZkv5z1+ZTJ+FrLCAPezljzfRsdFZpXrKdtZFuZ+omU=,tag:HVks4wGqLUfCIfJ3FJC9jw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNmVDY0dYZ0tsQm1Gd3Zl
            UUNSeC80NGlydkMwVFlkR0x3WGg5TEt2OTNzClRwOGV0M0NITVYxUzVqQlR2NWc3
            eVFxRTBZNlFublZSazlyTW5lcVoyVkkKLS0tIDRiTURWbE5CZ25iMXJHM2MzRmNo
            Ynl3YjVRaTdUejhqSjFYWVJudnl6NWMKLAo9RBYlHIJxadSA0CIhFJkREYoLUxr6
            A3XMX9nI0vs3Ix1VGY/apTo9mN6RNqUGWco0y/L1Uba3puDGvLO58g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T16:44:05Z"
    mac: ENC[AES256_GCM,data:Ivf1JqxrcYnXEIKCRefJ2s3sVA+iiXCnm0jVJXaNnsICEm3NL4CDCulS/d2zg+PdjgfF8EwqbvKvlOkLfPniYqGZDRsfOBb91a0X3q2zZzMnIpDPyjBCfeomlYNyg6ZoGOZ0jpsgl884W/hDaE96BiFg5LNWn3aNtXYBuEMn+pg=,iv:0uiPQAUkD2+3qsgZYvQmhxlrm+Srda5dAHoVCJ0y2LU=,tag:xzhLW2gjFehDJhomk0qYBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
