image:
    repository: zot.lan/kitti12911/grpc-sandbox
    tag: "v1.7.0-beta.2"
    digest: "sha256:bf014c8532920677b644eb9311db08ef286f17530c154fd2b58275f7ddeae08f"
    pullPolicy: IfNotPresent

imagePullSecrets:
    - name: zot-pull

configSecret:
    create: false
    name: grpc-sandbox-config

config:
    service:
        port: 50051
