image:
    repository: ghcr.io/kitti12911/grpc-sandbox
    tag: "v1.12.0-beta.4"
    digest: "sha256:df9310f92c67e2ada95ffb68dc63e0f7950855b40aae91433b48bb6a2cbfb9ba"
    pullPolicy: IfNotPresent

replicaCount: 2

autoscaling:
    enabled: false
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 100m
        memory: 64Mi
    limits:
        memory: 384Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: grpc-sandbox
              app.kubernetes.io/instance: grpc-sandbox

secretEnv:
    enabled: true
    name: grpc-sandbox-secrets

probes:
    readiness:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
    liveness:
        enabled: true
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3

config:
    database:
        database: user_service
