apiVersion: v1
kind: Secret
metadata:
    name: postgresql-payment-service-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hxKZCfuqqvgGAOFdCxyr,iv:4KkmbasvXyj2VC7qcqnIM+B46FdGn1fKJOmLIWUTDfk=,tag:Zm6XIvWWZ7GKgZTb7WnBng==,type:str]
    password: ENC[AES256_GCM,data:cCndAKne33WAAiIjzU5twuW8xSSiszqEARTkOMCBgw8=,iv:Ii0ZxYLBPtwndwF+DaqDf0gokrXVVZAFqUf6UZZaAtI=,tag:rF5TGEPz5FNqmG06ZdxKmw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM2tXM245NUtCdFBGZzZC
            aXBJRGEwRkc5SFNDVDdGZTBGbGtHUVVJMjJVCldQcUlEOFp4bDB4ZDlOVmdtU3ZM
            blk4aHVmYUN6UG1hc2I3TzRaRGZ3M2cKLS0tIHQ4eUVKZzV2czdHcm5lU0FuZ2hy
            UGZkbzhuNWo2aUhwSHVTSEhnc3V4WEEKwBX1m7Cc4YebFvLW3URZukaKoFtpnDog
            qpZHpEXmd2cs0PWS/2A6wzOD5Oocbzq9PRS5Xi0mUobmaDOYC1m1Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T11:42:55Z"
    mac: ENC[AES256_GCM,data:dlH+q68P3kgzravdNRIWYKIaAc2S9HQM6/rbo1lTfmO1vjt1vnsjZ9gloDdCrAoFe/vRpSrwnGnmemmeFt30xpTHJ7gai/6KKpq/+O87RotSg37JxVFuVg791b/KSAQlDyGvZxfHjkM72t80blYSUIKzzATfhaVYf/hyawjAp2U=,iv:F+eQ3+QMsxdW4Ir8MudHtQj+JctWjWVP5kdbaKrqhsU=,tag:w0e4ob/uutdORuN92V3fpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
