apiVersion: v1
kind: Secret
metadata:
    name: postgresql-mcp-reader-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cr+ws+XToAkbZQ==,iv:QrI+G5bFqRr1MBufRI9JWyxHz3c2ufVB4e6Xf8aJYlk=,tag:GYnkDXG4hsyeeAyFpcrNPA==,type:str]
    password: ENC[AES256_GCM,data:PP9LrLsk9XDsI5XgwT3NTeo5wp97s6sjYfWFBM+r+0o=,iv:ynmmmNqyu5pynTK+Ju5x5Md1r5W3uk+aTT7TYRru7y8=,tag:tV9pTLeOJQlOJZmTURED9A==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YWY3b0FFK3NITXZpZFpB
            anlSUytiejNvd2ZBRWgyOGRXWnNYU2lPOVFvCld2Z1M0TCtqeUtzblhERzdpdXVn
            bU92M0sxcFNsbVlsdkhYY3dJaDNHRVkKLS0tIGJUY2I5VEJOUnVGeWwvNmtRdkl3
            cUlxSGNLMGFSR0crL1hhZnVLdisxenMKiCpQeNQzT7uVqH4C1mKSdpUDdfOwfzKK
            3xJy5qCR5tkkUIOOCOklDQdqRz70L/94dWPEeYm7BHImu5PsJdy0vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T08:10:32Z"
    mac: ENC[AES256_GCM,data:PMn48R/lPU/8Q/sdR1+RevYm+BN/2hRC3+94Fmn12CuPB4dR2exjsxFlqnGdyZefg1nCCLyg944NkDJfOdmlKmp3J8n4EEDZ382B+oA6AhJyxRrCOC1IYTSitC+Ird5ZwLE5VJ3ELDE6zk7TuCwPbIZkXgN44HcRI3kaWub2KLI=,iv:T1P+ViPRb39wvBf6PzFw4azEMVXk30OukzvigihloXk=,tag:Qc/hVmwlxy5obTIejLR0jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
