apiVersion: v1
kind: Secret
metadata:
    name: postgresql-saga-service-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:DRMPUfM91gYIVWUZ,iv:TQq7oAtUfJJ1oUpRUF/PwPPXS70o8r0vZ6UnCLJWNfM=,tag:DaRiVZJtDv1eOGYWc3QOQg==,type:str]
    password: ENC[AES256_GCM,data:ns+vWwxniLV0fl5fpAjcFNilh2ydWhEbor3TGUXAsPA=,iv:JFMzp77kfh2PlffiFCmPXKEBHceRYsexEjqSbtGCkt0=,tag:QZ2GNjhRFJBETnj9cO+2Dw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTDJhR1BDY2lOWng0WENv
            VHRaMlo5K01pdFl4UStlNzc4M3NqVThONWtZClFLVnZDWTIwMmozTU9NeHNhbFg5
            cmVPejROTDVJYklxQThmd0NIRzdRRmsKLS0tIC9aVmpuSHNPdnF0eE01K3FYd2o3
            TVcwTENRazZCOTh6U2lBdkhMK0tXck0KYgGdZFJ/GZXe0QZSbPTn4JYu/DWqHrOr
            aBN5xUEQx0uW2FJyeUcjq0uuj13Rff/FL9HaGoAbrHUhBVCRLtEiNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T11:42:49Z"
    mac: ENC[AES256_GCM,data:XalgxlfM08ZLzcn6mzGttvQUl/mzqe28MrwPp/aO8AWjDyN115p23HybT5z7aRgF5jWttFteXJJRFinit1e0F+gDgRvFkH7k6DJtCgPhnEs6LY8CIjm0RCp3ifbAfAIZzkD0u86a9sLw0KXf7G3l9+9c4k13amX3s1MCVnqjJNw=,iv:9twExzJ/LHFT2ufNQ0BoAcoazOFu0uaoiPlvDKfoouE=,tag:rkR72nPpX0EY1atM0cMAcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
