apiVersion: v1
kind: Secret
metadata:
    name: postgresql-sonarqube-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nyYUw9wgW660,iv:J9yqij4vAX1+v1xowket4KwR9R+yZJHOU2UJUI8eILI=,tag:KDeTpLU8SwDB0BWLldozpw==,type:str]
    password: ENC[AES256_GCM,data:fVxW5rRUCkiO12no4uMGej1s/A==,iv:4cXHfpCApIpXGkH3QunF3nVUsPf06oaTgJqIe/Pl1Pw=,tag:dXERsu4xL3YkjFI3Bo4D5w==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTzF0UW03MndCVDh4QnVG
            RU8yVUIra3o4U1B0bGpOQjdxRGR1QlNMeHdnCjY1NWdhREJsRFh1d0RsMDdUSU5j
            YUpTTm5oRFJ0NFIxS2JySlNJbDRMK2MKLS0tIEJxcDFWWlhaSW5hazUwbko1RURi
            WmJVZlJ0VUs2MGlXK0lTcHExT2daa3MK2eOrS9v9QSDyN/XuBhgOQyb69BOawma0
            zVou6rL3Ef+54D444vDK7p+lEDXX4pkCZBFOeZcAqryEmzJ9268nkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:48:34Z"
    mac: ENC[AES256_GCM,data:WMz3i2izl5M998oEckEKxF9Zs1rYSCGxKC+G4vn4o/Rh1UJ5edHocVO9B19LyYdswUTWaOtdMXxfQxddfGxEH23oEu9avcIpU9dIm95p0rPKl3GAjHybpQe9h9UYKTH1nojIljSMWCjX2IY9WTZ+tgQ7m3SAs4VdTTm0DZuZPxE=,iv:95u0Z05xrsUrvGnK9K8rxCloe/AakWMNkjunoAUM8uc=,tag:g55QpGBrztZmJsd8pucAwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
