apiVersion: v1
kind: Secret
metadata:
    name: postgresql-user-service-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ryidwfWU9KXUu6xr,iv:NnzXcETR1FTx4UHGE6RVtPi83S1tlnoZbXibNG8bucY=,tag:T79pwKW8h0A8igT5Ku5xtg==,type:str]
    password: ENC[AES256_GCM,data:X9cc/Y1ckA8DDzaAApUT5W3Xc2dxSqiV/QXqBEDiXsw=,iv:Y4FY0Q5mdhnBGGnpUzfalNcN6De/zgQJCAtCcGyC2rs=,tag:kDw4xPq95E2qgpxyHkq9mw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK0tubmt3dFM5MXVFaFZ6
            WnMwWmFvZDlSSEg4UE5WT3NvRFVoNUVIY21FCjNXd1Q3Ym5SSmN0eG5BVWI1ZGZI
            bjZacC9mMlRGMWEvclovRWtrTWJ4aGsKLS0tIHJ6Nys5dzVRK1g0cHpaZmhrd0FI
            OTM1TXFIdkNLcVp5SFh4MU1Ccm9UZ0UK/2znJ0WhK48FHuic9tM52/P3e/hTcegz
            pRylzysVo5R9+CJJbdgWeXlrggtZym5yj4ofIfM1e1RakfHAsoU5Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:16:20Z"
    mac: ENC[AES256_GCM,data:UganzFRXrZ9CU2QSbtFc+TD3QkO6ocbuvhiVamVQ+UrbUFcQDiSrO0p9r8rN25OELLfGsug1jKaESWs7w2F1eo4Cy+ZfNBk1qp5Gfa3tKHlzaCRlW3FYdmDaaf5MZjhyzGPZJIF95FQoly8SHRZMioDNkY2mO+qScZ8iSWQ5dJs=,iv:ewreSjWsnLI6UZsZB4c/gRmp0/BRgmFgoW5UjWX+X4c=,tag:hq2O4nBwtNTe4ni3tw9OBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
