apiVersion: v1
kind: Secret
metadata:
    name: zot-oidc-credentials
    namespace: zot
type: Opaque
stringData:
    oidc-credentials.json: ENC[AES256_GCM,data:JOsuGbX8o7uvplpxA/aVJKZS+4nM51j7I7aJ7jBwTqVNYsSKqzh1rWZUWmHs5kk7/lUJEnwkJzLuRe85y0QVjDSlaXRJeGSv/ppdl6Qt,iv:Ik3knTCw6C24vaZAQsDfA4xLvHm2AlyMNo9dfnKCU/I=,tag:ikWSpAjRHvA9XSyiPyS6aQ==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cWtkRjh5Z2VMa0NRRTZ0
              dnd3dnBKWFdaWjNqQmxuR005ZXNLeDJmT3k0CjZPOElaeFdWdFRaOTQrS2JSSGVK
              Mnc3TmpkdHF3d3Y0amQ5TVl5cmpyS2cKLS0tIHExbEk5V204VEZGMzE1OW5zRE1O
              bEZKOWg2WWdKMDFrNlhPM2dUVmJCeFEKItdZDp/NCn9J4bNlH8YtgDOuxHK+ZSUR
              VqRH03QsLa8ojj0dnroA2pyQJqST3a0RYo+rjFqaA94hpwQH/FLKRw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:21:50Z"
    mac: ENC[AES256_GCM,data:bIJr8kAJMwVy8DARICS0jF5KawBCjDbZurnOscWw9jqBHM0ODF2YWbVmAHSxVQVRL2c40iGlLd1hurAVRNoIf3nhuoWkoYXLSXlAXo9aUNrvtc5zmSK5ZbEjUHvBIKgNhqT+zJZk5ff+ocNBsGwC2AtlDHFpAM6t703ffmf2J4I=,iv:XLvVs05TCmfClQDPqJzplmC3M+A+qA3Hr44HO4U9X1I=,tag:n0fiAaP93/47mnBuR5bFLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
