apiVersion: v1
data:
    session-keys.json: ENC[AES256_GCM,data:f9dAsMUqsgSiEnwT2e5WYtryDdxWQcBL/ivPnptPSG6phUPqvV5YCYrq4TT8KgD/PDCZ58T+kZsgR/bmwChzQHSQ+OBxUN5bOmkTHXci8p6DBLJJDu+hWPXact15app1Iik3i6F7w7N2/vRpX2Q8XACtXKECoZ/znuIbA18lnzfWsJELCeuES3YByPDN/T16aglfpEwitOpcbJuZkeA/GSrL6hHWb1nP,iv:JNaco90KKhSDs7NrwDT3yCbAW2SmRwuJigbp7UCfPHY=,tag:vn2ZY/FJxey84J4dhhMJLA==,type:str]
kind: Secret
metadata:
    name: zot-session-keys
    namespace: zot
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ1lqNzI4eXAzYVZ6eHFG
            TWtQVzVvMkN5dFZQaGJiL2cvbjJpelhkYkQ0CkRrU1dkUnM3eEdDbG05aU51ck1r
            SFZBWXBLSUN3ZnNOcFUySkZqVjl4SVkKLS0tIENnUTMzcldta09iTzBaZFRyci93
            UFhDalFmdnhuaWthSlB5LzMvUkNEQzAKEroNgJxqD8DE7xQ8s0ZDMwwTqTvWmj/a
            3+VZAdtCYcBwbc1RnJelRYWVNI1hqrl9IZtzHOMLe+KSJVzyBHdDzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T17:00:20Z"
    mac: ENC[AES256_GCM,data:er/HZlIg+H2HV00lqclG9Mpjkamqmix5SOVlWgeSJDO8j/5E27HwYqIKAi5v5Pu9GSSXeOettrPwQ/kBEbfKNsqX3c+Os1TWtpbA58TMb7MmbkscG/rjgyZdnHuybkMK7E1pqaD2ZajdQsXGGOifzPfE23VDKFJJ/Lr/CycAUNE=,iv:mcM+FJMGKDJxSfaNAdFGPwFp3H13qvXI9z3otbcHTnQ=,tag:eQKs20MmDBX5d9FVd48cwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
