apiVersion: v1
kind: Secret
metadata:
    name: worker-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:ScN591dMd6y8qBYSqDUe+4qfu/cNV4aw6yRSazo10feqbb/Y6t/FAMfRyyEUSKiHuDQy//Y9/aq7dsJp6TmNenkQlyilak8+y676zdwz3wnLUmq71LqD6F8V0No+jB3VSZqj7lfnWUlToQooIsFX+I1RexVQ7PYByGUhUaqfkQeDR0Fw4YwAYPIj3hiVC07GUo9uK/9rNjtlY4ebwpcerDUJ/nVkLDYdlNGWLQKldN52+qWHuJ0U9u12jyTF7avCJkKpkQE3eBjLUSTY4xSw6dF5d+rSxZvsqoByejCr6KBEOhqsduHAX9Sj58VdQ306zNHRBwFyyE35xWfQLHEXlyj+jWdHJmSjnLvIf59HoKhpgxbSZfw1Gr+O1CfqhhtdakQSug6uRIo6ek74d5dQvbvoWmTyfCt3mwwjd+0214hcOLWDJ8FdZqeLAphyNyPBFIRbVSk4A3CMqk9zZP1lmi8ZPwSJ0W+p9NyinzgxwVaytiZXzjYbyh5WqI6Ob56ILlZ/9JisIiP8KkK1qibuSGBrq6cTHP/RSevVI1Z8jPK/V+PqLQaf09d3C5YHMQCgf88mVbqjzwqUf5lCqtaD0UZfvC1BuHtzapfRXXtAYUWK7reI8lPO0UG54gHBeREuloIOTsFW3HVGRhVnYPwBOwDa1O6/ppMfcXFFqnNPJgJ1YlQ9x2BkvfgtD8sXPfTPtP0UZOedlUchltHz/ZRix1iDlR3qafCxSzlgqYJHgcfbwkspNTbAYYxYMFs5KbnHEy0T2Awhj28fapK48F7r63uTSEfWr0YQJP9lA3DvVLxXzDMRdGhmFJFTHl9XozpbBZNBOX0ICIs5Xd7SFkoDtQCuvvvw/B+cNAOHonoPNKZZQnSRSliNZaL5mLFXdHKEfVOJQoaLIA1CilY4DIFhT8iyyAc/m430HoVrQdP4D5nnvl67Ke3dFXmuHpiw75/Z2l2cXOHHz3u1fFC0PnPuywu566CaBbVhMRb/e1tOxpN1KILksYiIIGd0e1dKySYVMLBcPd3FhZ+JQNbjZwXO0SGxX+suw0Dq27dpzMEgdJeRzmrNIpiduvjIY2sLaAg7KmITsbmP7vImI1MAf158bjnbmohBL/a/y/3ygbweXeBunRKaTYTDH71WRjJnWXtCNoHQBcwV188ITp/KP2fY/9mmPcTLSegSLQcCOY4O8VA2JEbf7QKGAdpyQFmFcdS47aahoNNKVKOrW+tco2ZsCQU7mrr6EpL97K0=,iv:Tl5j1lcGDdU8MaMgjH5s3Ksf/jU1X2lx/Md5l671Kes=,tag:AEAgVq+J7Gna12UvTDGCCQ==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aGFQSDZMdmpZWEl6ZS9O
            VWd0VS85NDRJbEIwdEJwU21ZTVVheGhBV25vCkJ1dDRnMHllemhnSjhvWHVQR095
            TithS2lLRWdzSGFwWVZVeDRrZC9HeDQKLS0tIDlTRER3MUZsRzkvdUM5Wmc3K28z
            cDhzMWwrWko1RWV4b0o1ZVlhZUZLTzAKjUq9vEahZY6aHn1WnOHvd1frM1aZwVa6
            rKw4NI1NswYHxw24iU+QwdHr/KGHd/XM6sMfW72E94zMob2+ZtkPkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:21:38Z"
    mac: ENC[AES256_GCM,data:T8taMmxggvj/ksJnEQUJDiXhn2xiYl9iZkIbErlv0GC/ydwwW+kgjny4MCY43NKKZEw2dMT/Ox6tahciWyJ0lln2ppnqV43o5Z/u42lE9kksOT5FO5/q02nNcmxAPApsvVTIL9WPnY3vGo7K7UL2sDsoo8ceMLbWqft1iMaST7A=,iv:GTZqwS3REKP5dlKq+ZzSy3Gl2UwzxKBt7fdv3nWKjp8=,tag:d0O+DCUZFCjJWojj11efPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
