apiVersion: v1
kind: Secret
metadata:
    name: worker-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:E6YDAxqX2nQCGu4ii7kwgaC61haCzCWh010jvxocdYniAS43B+XQP6erkYmtI+jhB2MDd9z4Xabsgf1AqCgG+CFMXPsPOxm8MLyUkTOF5/z5adfxGmnf2+n9c17ZoxEq4mwz1sCsLiHf6PJ0Q/rT8RPWCimpiYYVfnG2DgntjLoeC0jSNmwBWNmvIz2SUReidlw2YDbe4HNT6ugKj3s5/gqt69twFmC25eaL8HKIb3n0hz0wlJZqpY/3Hz/p/gvkY1pJMPxrzaCnWclhHkvISlqf9PTE8/VSW6k5bB5N+HeOAlY7TWF8adot3ZxoImVnQODukDQO2MHtO5TJ06qpDBoaAZ9QrLlX1Yv2fGnCcG3F3n7dlbME2r4vP7Q6GHyxy+ijPlu16/NE8acVWMjcyvjKMBYc18oaEKFv7TWSeuGDYmxZD8zcOMLDI5NYnOMlCaOSGTvUjtJ+kCL0mF7tRg+LVX/oVMTB/nsj/tBU/UZB3dhuXPIc5mBIf47uFwJYqNqvMRH1umeyXvG8XATz6VNZryZ2uY++fJJtY9itmg84Cy9uWJJ5f1uErn/U7/tV3be/XMSfcsCwmsSY0HKgC72jg83sVZjsGk0LzXpHTkPMvALa16nYFYxELyakX1Ku7NLnChef+8MbuKvAxGbjSwWInbGPnDSN8nkPGT/7EJ6Kkv4+XT18E1iJi20GJdFA6Dt7HrnHapJahCyr86KVXmdukI+NHpws8Utx0m0lgfmME+cUKVDdkWpMrDALlovUGEvRYtEN1EPP9RjaJSxo+wfQCwt6gSc9hSS6ntwjxLOJaSYuZ/ntqAhBfFkhUid/wRac6/fw3Maves68bWAyUX55KOFM3VWIWjKBxDiypitu71zuzOTclQyGL2H3ap9jLcKLIXPPMQ+TukKGzXY4B/KoDLcwteNzySu2nJjkwzkMmICSR5sQ8vIWpBwA6y31dKjV7MsOQ6ftfULkEeEIU4bsVxsIeVSIm5vkHHo9lGwTe2mSEibkovqQab9RmtTqMBgu7Q24+HMg45MO20TFCezBNpUpItA/JfOxBxshokHuoJFi+6qurw3mWRnVB8NDjCs/r4dTRHqP//2NYlw0cwUqbqzSryIof12zCMkT2aE1I0zql8CfORd1u6fU2d6DgqXqsSAC2eEb1oLTSPQimOxXw9c8WwctZOuFIcUzmfB3of7O2EQXcFKpuq/QvyXUM7yNRxWapAsfHOEAWNgw1xmYRsOTQPjGcPc=,iv:kIArPQBveGra6hSK2za+6YdHwVgLkOs0kQ7DLSA3lZk=,tag:RzxAmwiOmv7Dkyc3w9BTYQ==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SWlrU3lWS0tJQmJvcmx1
            NHFObDNDaTdEUVZ4MFAvbkhwbGdxTFFCeGlZClBSVE8zY1oxRXBodnM0QUgxRmZq
            SGxQQTJGcHZkYUlBbzdnUEJCdk1BeDQKLS0tIHZJOGt3OFJGYjdYZ1pqaVNpMnY5
            d0NaZUtpMyt3R3cyVCt2MDRObUpSbzgKhQ/gaf9LoGAo4rHz4DI8ZuSS8MO/GkHw
            hBiYMpx68kjbf7tSX5f9Ox5tfoKZStTt8nviHGtANZ35iddJx83JgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T17:03:28Z"
    mac: ENC[AES256_GCM,data:FpIW/ShHbggRae/qo+wkidtk2zQDlGZOH7/QyefP0jU7AkzicpRwLc4VLoqkIiQxPB/+iZDaaasdT80p/c6XhlwXpeG8Jx2wcJbe0Tl/Tmjyo33CE5DDT5Dvuyw2dvclV+IfasXJmwVfxPo0Camy1jD/8sujULfOf8RzsUfWwGk=,iv:PsyXwc+au8xN9xXt2mWQDfKOWhX5NdXg1uh7gxuEzqI=,tag:h7+iHdn8MZG99nZ/v6oEYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
