apiVersion: v1
kind: Secret
metadata:
    name: worker-sandbox-config
    namespace: sandbox
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:YydkG3Efaf9+EnDErPiVUEZyVTF4Dm0Lg5hyWl40KtX1OXWrq8VkBIOtxMqHlWqmpmwMfn48zxBpCIjaFWjbU6oScvadhocNi0Du6iv+fcIsSUfjHx3zXlOjs281+ag3LQjrzf0p3vEBVP/JP2e0pION5/Re64iSP5v0+FSLXmLTzNV/Urg5u+EMzWfLTe+kZ8bD3gGWUJafTP05BiHuazZ+B19mfoeqFMTuF9kcna1bHoir2NmpTXBBQS4CTa6++2+TYl7y4VFRi0hICFmC8+C4+zok1vpgPQlA1946NVntBqjTLd0187ChU8WJ2ZqbW3G2CS4Ka7nHGtRqJsohHxc7uC4f6LIseO5vRxwGEHpj6yjU8qm8pjy4saimprTJBcYWZPl/TO2Y2zpyZDVzWzG8LoDeXfNvXYSgna2c0Blmc+rJAqqsq5ziCyF+wMkD/twHZlapLm3df7DXOhTcHgvOlAATJpHYjmziI3n0DjxmSP3yQgQ1cCd3kwDN9Utjd/bwetPB3kUQaxNFcY2h/WMGVvPQnrtjLC75FiWLa6CDtwZ32YqIG25EYQsRGJGRJ7ruEqpWZ098CmB1zwozvqXm6nsYyy018vyOzc4dpF+uhvgsqs75cIbmGec+6keYqfXGOAiMtgfVPUIcRQXNrT3JgiBnYo1Q/Vrss4NYf8BL+mN1t/Ry3PIlYBKEsIn5g06aRGJb9ixM6M//l41Y59IVzCQGagZENCLueEVhyeKRFKAoDvudbs2uARMB6vWM3UwsqWJRLVu6/pIDh98yFdpPgk3QJodhhSkS0gVNrQ5YuP8U3PV+6OCEn4ynodvmaDHhaRSAVEmX8fBrHL+um14Eja8tVmYNN8gn8W6AGrHnfdbjxnUZlxxUuZPOiEIiVSR6u2hGDguwilXltOuFIB9QjU7sH3h/j+nM0iDxSl/Sa8ITHURErqOHiOkscqPsa9p6X62iOyz3HW3iDq5BXDyRWcFPzwBnupMdu7jXXZsr2dqJ2PxytVoKX5YtvYKodMiSkdgAJXCdmxFeU+7/Zk0ZLybsJVvqW2xyttQ4ycB3yPG93WihKyinP+/T57pESZYCpwnWICjk/AfY+nrmxjW+Sbf9XQTJBKr5GH05M9nTX4VfEXTG3bUnUVCCWA6v7ztYX4oXyV1Q2rw2cx4E+TAe1j+QljQHtHlZihI8F0QQawV+PI8oKUBwRApo0PLRsQIpBvkAVLWKZYTiwnOwEEBu1KMrdPrVp3s=,iv:2H3QToGZhGjjZRdiR6rrJzpH5yLHwMIkZBUh8Zd8p/4=,tag:GFRz+5YJtX6b0ScGQCRRag==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UkxaQUl4T0x1c3BDK25Z
            SFRibE9Ic1cwNVpocWw2RzEyNDNDR3R4dzNBClVjYTVQZDlKTy83UXRWUWlHdktP
            OURjandvcGlGajZiS0g0KzgzMTh2VFEKLS0tIGN4TyttMi9heElVY2dURDJ2QjZm
            Y0E3MW5DV3VPeFJhNUJ5RTF3T3NwdVUKn2SkvzNTgBBGlHpO7IUrtCCmUydlABUV
            7DmNN2+nJRMLRSIWx044lSqySWDjHTuo0ZFU5lCrZO2w6cJNsvuWQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:48:46Z"
    mac: ENC[AES256_GCM,data:QFhOKLHHSZPex4DSU8ww1alRO98u7rWNyj9dPicPHSICqlJq1/NP8sfRuXxtC8ypPETvPt528Xynh48ckzLle4aKyyYf+Ua/OsOyj+FDF7nPQGZIu3dSleq23DGY/yzxcWEv4xop8K/znsrg7Wlh6NPD1xrYOptZThVcjEIrtYQ=,iv:g0BXaLS3MUHDbUd57PCFbu72LiDy4AIi2Fj/TayEl80=,tag:FakxlkQIdauDnoXq+Y1zAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
