image:
    repository: zot.lan/homelab/worker-sandbox
    tag: "v1.5.0-beta.1"
    digest: "sha256:b9e1d4fccbb73f5b8371bbdb44e6397ad8f516bf5f94556e48270e48195437cf"
    pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets:
    - name: zot-pull

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 25m
        memory: 64Mi
    limits:
        memory: 256Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: worker-sandbox
              app.kubernetes.io/instance: worker-sandbox

configSecret:
    create: false
    name: worker-sandbox-config
