image:
    repository: ghcr.io/kitti12911/worker-sandbox
    tag: "v1.6.0-beta.6"
    digest: "sha256:dc86e47c3d61f5d605b1913255c10a9a78af28e607c792c6bdd171d64e2b7a32"
    pullPolicy: IfNotPresent

replicaCount: 1

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 25m
        memory: 64Mi
    limits:
        memory: 256Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: worker-sandbox
              app.kubernetes.io/instance: worker-sandbox

configSecret:
    create: false
    name: worker-sandbox-config
