image:
    repository: ghcr.io/kitti12911/worker-sandbox
    tag: "v1.6.0-beta.2"
    digest: "sha256:4c31a1f1b09645e2c2a0d51f0d1a4ce56f06873ca9d69eb8af911199c1baa564"
    pullPolicy: IfNotPresent

replicaCount: 1

gomemlimit:
    enabled: true
    percentage: 90

resources:
    requests:
        cpu: 25m
        memory: 64Mi
    limits:
        memory: 256Mi

topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
          matchLabels:
              app.kubernetes.io/name: worker-sandbox
              app.kubernetes.io/instance: worker-sandbox

configSecret:
    create: false
    name: worker-sandbox-config
