apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XRPYsrImXNs=,iv:hdJ1Z43lS/LDHl/XIIg1/TM5tVZ2M5mkEo3QF43zLn4=,tag:64Em6TQvUSIKTBU0mPTeFw==,type:str]
    password: ENC[AES256_GCM,data:mKiz9VJwXdfI1TI2pIedBSBK4w==,iv:e9ieIDofxwE4L9WyxKZBdEvyhVq2b23puC944s4m9gg=,tag:MFrEBwpkXKXB5u2qSC/ivg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdm1Ga1haQkU2cGRuSU1O
              dHV4Rk43YVVmdFlqSE9SREFxTk5iU0xEdGxFClM3aTJ5VVkyZ0RETG5MaGIwc3BO
              VUtEdC9ibTcrZkZ2RmMvd0NmOVVhZkUKLS0tIHFpMWsyNmlLOGtXekxkRzA2WmJm
              VFo0QUJLbXB2a3BQUDhzS25zSndQbk0K6gI1N9zbyE7g8U6cMgGjuEqewBYeUc2i
              +X54sG5gdQXdZ4BBK72zhKV4jPKFakAjH/J/u/xCt0NPaL48KRWNww==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T16:56:20Z"
    mac: ENC[AES256_GCM,data:J/D0IXN4MreQA3VDvifXkFsuI0M3/IlXqJsUs4DDfR/ut75+6UjKCKNW8KM9K5l/5DJlyBhi+Udv5YW5ONMJOlnjt2yb82Pf6Oh9PsGlqskvtGGaveWzl9N6SAT+h9djnSVcfn03X/PQgmkn+WohRsT6/ZnjbCk4q5LQEZ63gpQ=,iv:nXxxrLPHqDQCNqiKIuB270ybFxLr0zBk6bn0+Ko/PLA=,tag:1Qfz3tabDra/C+Zo3IgKhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
