apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: auth
spec:
  instances: 1

  db:
    vendor: postgres
    host: postgresql-rw.database.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  ingress:
    enabled: false

  hostname:
    hostname: keycloak.lan

  http:
    httpEnabled: true

  proxy:
    headers: xforwarded

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  additionalOptions:
    - name: tracing-enabled
      value: "true"
    - name: tracing-endpoint
      value: "http://alloy.observability.svc.cluster.local:4317"
    - name: tracing-service-name
      value: "keycloak"
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            env:
              - name: JAVA_TOOL_OPTIONS
                value: "-XX:MaxRAMPercentage=75.0"