apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: auth
spec:
  instances: 1

  db:
    vendor: postgres
    host: postgresql-rw.database.svc.cluster.local
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  hostname:
    hostname: keycloak.lan

  http:
    httpEnabled: true

  proxy:
    headers: xforwarded

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            env:
              - name: JAVA_TOOL_OPTIONS
                value: "-XX:MaxRAMPercentage=75.0"
              - name: KC_TRACING_ENDPOINT
                value: "http://alloy.observability.svc.cluster.local:4317"
              - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.observability.svc.cluster.local:4317"
