apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nui-data
    namespace: nui
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 1Gi
